### PR TITLE
Feature/edit house

### PR DESCRIPTION
**Pull request by sansive**
## Task
* Create editHousehold activity.
* Check if the current user has any household.

## Testing
None. Cannot implement tests until the firebase mock is ready.

### CODE REVIEW

**Comment by Arkadyus** [comment]
The edit house activity looks scuffed on my emulator : 
image

Not sure what causes it but it definitely needs some tweaking

**Comment by Geno22** [comment]
image
I don't know why or if it is just me but when I click the return arrow it crashes the app.
Also the button appears behind the android band at the bottom of the screen.

**Comment by sansive** [comment]
> image I don't know why or if it is just me but when I click the return arrow it crashes the app. Also the button appears behind the android band at the bottom of the screen.

Yes, there is a bug #105 planned for next sprint about it

**Comment by Geno22** [comment]
> > image I don't know why or if it is just me but when I click the return arrow it crashes the app. Also the button appears behind the android band at the bottom of the screen.
> 
> Yes, there is a bug #105 planned for next sprint about it

Alright so maybe just a fix for the button then
So it is prettier for the presentation

**Comment by sansive** [comment]
> > > image I don't know why or if it is just me but when I click the return arrow it crashes the app. Also the button appears behind the android band at the bottom of the screen.
> > 
> > 
> > Yes, there is a bug #105 planned for next sprint about it
> 
> Alright so maybe just a fix for the button then So it is prettier for the presentation

Yes, the button already redirects to the main screen

**Review by Geno22 — APPROVED** [review]

**Review by aindreias — APPROVED** [review]
I'm not very familiar with the house-related side of the app, but everything looks ok on my phone. Thank you for the contribution!

**Pull request merged**
